name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute SSH command
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/feedback-app
            git sparse-checkout init --cone
            git sparse-checkout set src/frontend/feedback-app
            git pull origin main
            cd src/frontend/feedback-app
            npm install
            pm2 restart all
