name: Build and deploy React app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies and build
        run: |
          cd src/frontend/feedback-app
          npm install
          npm run build

      - name: Archive production artifacts
        run: |
          cd src/frontend/feedback-app/dist
          zip -r dist.zip .

      - name: List ZIP and directory contents
        run: |
          pwd
          ls -l src/frontend/feedback-app/dist
          echo "ZIP file path:"
          find . -name "dist.zip"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'citizen-feedback-enhancer'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./src/frontend/feedback-app/dist/dist.zip
