name: Build and deploy React app to Azure Web App - citizen-feedback-enhancer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd src/frontend/feedback-app
          npm install

      - name: Build the app
        run: |
          cd src/frontend/feedback-app
          npm run build

      - name: Zip the build output
        run: |
          cd src/frontend/feedback-app
          zip -r build.zip dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-zip
          path: src/frontend/feedback-app/build.zip

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-zip
          path: build.zip

      - name: Unzip artifact
        run: unzip build.zip -d dist

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'citizen-feedback-enhancer'  # 替换为你的 Azure Web App 名称
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: dist