name: Build and deploy React app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd src/frontend/feedback-app
          npm install

      - name: Build the app
        run: |
          cd src/frontend/feedback-app
          npm run build

      - name: Change to the build directory
        run: cd src/frontend/feedback-app/dist

      - name: Zip the build output
        run: |
          zip -r ../../dist.zip *  # Ensure all files are zipped from the current directory
        working-directory: src/frontend/feedback-app/dist

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'citizen-feedback-enhancer'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: src/frontend/feedback-app/dist.zip


