# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Node.js, GitHub Actions, and Azure App Service: https://aka.ms/node-webapps-actions

name: Build and deploy React app to Azure Web App - citizen-feedback-enhancer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd src/frontend/feedback-app
          npm install

      - name: Build the app
        run: |
          cd src/frontend/feedback-app
          npm run build

      - name: Zip artifact for deployment
        run: |
          cd src/frontend/feedback-app
          zip -r build.zip dist

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: react-app
          path: src/frontend/feedback-app/build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: react-app
          path: src/frontend/feedback-app/build.zip

      - name: Unzip artifact for deployment
        run: unzip src/frontend/feedback-app/build.zip -d src/frontend/feedback-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'citizen-feedback-enhancer'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: src/frontend/feedback-app/dist
